sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t66iBAjfnbGHeqaxWsd
    access-key-secret: DGwCdBzALERosO1EnVIEIVJrUbTk8u
    bucket-name: sky-take-out-prod
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx732456a6aa1dbae0
    secret: f60c23e095132ba4608010df7ff51b1a
#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: C:\software\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notify-url: https://464e084c.r27.cpolar.top/notify/paySuccess
    refund-notify-url: https://464e084c.r27.cpolar.top/notify/refundSuccess
